# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: QECalculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12QECalculator.proto\x12\x02qe\"(\n\x05QEvar\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\x12\t\n\x01\x63\x18\x03 \x01(\x02\"\x14\n\x05QEans\x12\x0b\n\x03\x61ns\x18\x01 \x03(\x02\x32\x31\n\x0cQEcalculator\x12!\n\tCalculate\x12\t.qe.QEvar\x1a\t.qe.QEansb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QECalculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_QEVAR']._serialized_start=26
  _globals['_QEVAR']._serialized_end=66
  _globals['_QEANS']._serialized_start=68
  _globals['_QEANS']._serialized_end=88
  _globals['_QECALCULATOR']._serialized_start=90
  _globals['_QECALCULATOR']._serialized_end=139
# @@protoc_insertion_point(module_scope)
